site_name: ClassIsland 文档
repo_url: https://github.com/ClassIsland/ClassIsland
site_url: https://docs.classisland.tech/zh-cn/latest/
theme:
  name: material
  logo: assets/logo.svg
  custom_dir: overrides
  favicon: assets/favicon.ico
  language: zh
  features:
    - navigation.instant
    - navigation.indexes 
    - content.code.copy
    - content.code.annotate 
    - navigation.footer 
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到系统主题
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
extra:
  analytics:
    provider: custom
    property: foobar 
  social:
    - icon: material/web
      link: https://classisland.tech/
    - icon: fontawesome/brands/github
      link: https://github.com/ClassIsland
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/q/7BWNv3FcjK
nav:
  - 首页: index.md
  - 应用帮助:
    - app/index.md
    - app/Basic.md
    - app/ProfileSettingsPage.md
    - app/ClassPlan.md
    - app/TimeLayout.md
    - app/Subject.md
    - app/Notifications.md
    - app/Advanced.md
  - 集控:
    - management/index.md
    - management/client-identify.md
    - management/connect-to-mgmt-server.md
    - management/configure.md
    - management/policy.md
    - management/tutorial-create-management-config.md
  - 开发文档: 
    - dev/index.md
    - 开始:
      - dev/get-started/devlopment.md
      - dev/get-started/devlopment-plugins.md
    - dev/basics.md
    - dev/events.md
    - dev/uri-navigation.md
    - dev/components.md