site_name: ClassIsland 文档
repo_url: https://github.com/HelloWRC/ClassIsland
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  language: zh
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 浅色模式

    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: 深色模式
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
nav:
  - 首页: index.md
  # - 应用帮助:
  #   - app/Basic.md
  - 集控:
    - management/index.md
    - management/configure.md
    - management/policy.md
    - management/tutorial-create-management-config.md
  - 插件开发: plugins/index.md